---
backend:
  name: github
  repo: travis-christian-assembly/tca-website
collections:
  -
    create: true
    fields:
      -
        label: Title
        name: title
      -
        default: media
        label: Type
        name: type
        widget: hidden
      -
        dateFormat: MM/DD/YYYY
        format: L
        label: Date
        name: date
        timeFormat: ""
        widget: datetime
      -
        hint: "* Supports multiple selections"
        label: Categories
        min: 1
        multiple: true
        name: categories
        options:
          - 主日信息
          - 主日学
        widget: select
      -
        label: Body
        name: body
        widget: markdown
    folder: media
    label: Media
    name: media
    slug: "{{year}}_{{month}}_{{day}}-{{title}}"
locale: en
media_folder: static/assets
public_folder: /assets
slug:
  sanitize_replacement: _
