backend:
  name: github
  repo: travis-christian-assembly/tca-website

media_folder: static/assets
public_folder: /assets

collections:
  - name: sermon
    label: Sermon
    folder: sermons
    create: true
    fields:
      - { name: date, label: 'Sermon Date', widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
