backend:
  name: github
  repo: travis-christian-assembly/tca-website

media_folder: static/assets
public_folder: /assets

collections:
  - name: sermons
    label: Sermons
    folder: sermons
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
