---
backend:
  name: github
  repo: travis-christian-assembly/tca-website
collections:
  -
    create: true
    fields:
      -
        default: media
        label: Type
        name: type
        widget: hidden
      -
        label: Title
        name: title
      -
        dateFormat: MM/DD/YYYY
        format: YYYYMMDD
        label: "Event Date"
        name: date
        timeFormat: false
        widget: datetime
      -
        hint: "* Supports multiple selections"
        label: Categories
        min: 1
        multiple: true
        name: categories
        options:
          - 主日信息
          - 主日学
        widget: select
      -
        label: Body
        name: body
        widget: markdown
    folder: data/media
    label: Media
    name: media
    slug: "{{year}}{{month}}{{day}}{{hour}}{{minute}}_{{title}}"
  -
    create: true
    fields:
      -
        default: speaker
        label: Speaker
        name: type
        widget: hidden
      -
        label: Name
        name: name
        widget: string
      -
        label: Title
        name: title
        widget: string
    folder: data/speakers
    label: Speaker
    name: speakers
    slug: "{{title}}_{{name}}"
locale: en
media_folder: static/assets
public_folder: /assets
slug:
  sanitize_replacement: _
